name: Continuous Integration
on:
  pull_request: 
    branches:
      - luke_branch
  push:
    branches:
      - luke_branch
jobs:
  integrate:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
