name: CI

on:
  push:
    branches:
      - Andrew
  pull_request:
    branches:
      - Andrew

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Test
        run: npm run test