name: My Workflow
on:
  commit: 
    - main
  pull: 
    - main
  push:
    branches:
      - main
jobs:
  hello:

    runs-on: ubuntu-latest

    steps:
      - name: Install npm dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run tests
