name: Continuous integration

on:
  commit:
    branches:
      - calli
  pull_request:
    branches:
      - calli
      
jobs:
  install:

    runs-on: ubuntu-latest

      - name: Install npm dependencies
        run: npm install
      - name: Installs packages
        run: npm run build
      - name: Run tests
        run: npm run tests
