name: Continuous integration

on:
  commit:
    branches:
      - main
  pull:
    branches:
      - main
  start:
    by:
      - user

jobs:
  install:

    runs-on: ubuntu-latest

      - name: Install npm dependencies
        run: npm install
      - name: Installs packages
        run: npm run build
      - name: Run tests
        run: npm run tests
