name: Continuous Integration
on:
  commit: 
    - luke_branch
  pull: 
    - luke_branch
  push:
    branches:
      - luke_branch
jobs:
  hello:

    runs-on: ubuntu-latest

    steps:
      - name: Install npm dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run tests
